services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: apartments_mongodb_prod
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-your_secure_password_here}
      MONGO_INITDB_DATABASE: apartments_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_prod:/data/db
    networks:
      - apartments_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: apartments_backend_prod
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3001
      MONGODB_URI: mongodb://admin:${MONGO_PASSWORD:-your_secure_password_here}@mongodb:27017/apartments_db?authSource=admin
      DB_NAME: apartments_db
      CORS_ORIGIN: ${FRONTEND_URL:-http://localhost:3000}
      API_PREFIX: /api/v1
      JWT_SECRET: ${JWT_SECRET:-please_change_this_in_production}
      JWT_EXPIRES_IN: 7d
    ports:
      - "3001:3001"
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - backend_uploads_prod:/app/uploads
    networks:
      - apartments_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: apartments_frontend_prod
    restart: unless-stopped
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${API_URL:-http://localhost:3001/api/v1}
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - apartments_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  mongodb_data_prod:
  backend_uploads_prod:

networks:
  apartments_network:
    driver: bridge
